easyTest/authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp
import os
from pathlib import PurePath

app_name = PurePath(os.path.dirname(__file__)).parts[-1]

urlpatterns = [
    path('login/', authapp.Login.as_view(), name='login'),
    path('logout/', authapp.Logout.as_view(), name='logout'),
    path('register/', authapp.CreateProfile.as_view(), name='register'),
    path('edit/', authapp.EditProfile.as_view(), name='edit'),
    path('password/edit', authapp.PasswordChange.as_view(), name='edit_password'),
]

easyTest/easyTest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('mainapp.urls', namespace='mainapp')),	
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

easyTest/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp
from pathlib import PurePath
import os

app_name = PurePath(os.path.dirname(__file__)).parts[-1]

urlpatterns = [
    path('', mainapp.MainView.as_view(), name='main'),
    path('redirect/<slug:slug>/', mainapp.UsersRedirectView.as_view(), name='redirect'),

    path('test/create/', mainapp.TestCreate.as_view(), name='test_create'),
    path('test/edit/<int:pk>', mainapp.TestEdit.as_view(), name='test_edit'),
    path('test/<int:pk>', mainapp.QuestionList.as_view(), name='test'),
    path('test/<int:pk>/delete/', mainapp.TestDelete.as_view(), name='test_delete'),
    path('tests/', mainapp.TestList.as_view(), name='tests'),
    path('tests/staff/', mainapp.StaffTestList.as_view(), name='tests_staff'),
    path('test/<int:pk>/export/', mainapp.TestDetail.as_view(), name='test_export'),

    path('question_create/', mainapp.QuestionCreate.as_view(), name='question_create'),
    path('question_edit/<int:pk>/', mainapp.QuestionUpdate.as_view(), name='question_edit'),
    path('question/<int:pk>/delete/', mainapp.QuestionDelete.as_view(), name='question_delete'),
    path('question/staff/', mainapp.StaffQuestionList.as_view(), name='questions_staff'),

    path('results/<int:pk>/', mainapp.ResultList.as_view(), name='results'),
    path('result/<int:pk>/test_<int:test>', mainapp.ResultDetail.as_view(), name='result'),
    path('result/create/<int:test>/', mainapp.ResultCreate.as_view(), name='result_create'),
    path('result/edit/<int:test>/', mainapp.ResultUpdate.as_view(), name='result_update'),

    path('category/create/', mainapp.TestCategoryCreate.as_view(), name='category_create'),
    path('category/edit/<int:pk>', mainapp.TestCategoryEditView.as_view(), name='category_edit'),
    path('category/<int:pk>/delete/', mainapp.TestCategoryDelete.as_view(), name='testcategory_delete'),
    path('category/list/', mainapp.TestCategoryList.as_view(), name='testcategory_list'),

    path('test_time_is_over/<int:test>', mainapp.TestTimeIsOver.as_view(), name='test_time_is_over'),

    path('groups/', mainapp.GroupList.as_view(), name='groups'),
    path('group/create/', mainapp.GroupCreate.as_view(), name='group_create'),
    path('group/edit/<int:pk>/', mainapp.GroupUpdate.as_view(), name='group_update'),
    path('group/<int:pk>/delete/', mainapp.GroupDelete.as_view(), name='group_delete'),
    path('group/<int:pk>/', mainapp.GroupDetail.as_view(), name='group'),

    path('students/', mainapp.StudentList.as_view(), name='students'),
    path('student/create/', mainapp.StudentCreate.as_view(), name='student_create'),
    path('student/<int:pk>', mainapp.StudentUpdate.as_view(), name='student_update'),
    path('student/<int:pk>/delete/', mainapp.StudentDelete.as_view(), name='student_delete'),

    ]

easyTest/templates/base.html
{% load static i18n %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% block title %}
        <title>Base</title>
    {% endblock title %}

    {% block styles %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href= "{% static 'css/style.css' %}?v={{ VERSION }}" >
    {% endblock styles %}

    <link rel="shortcut icon" href="/media/images/favicon.ico" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">

    {% block javascript %}
    {% endblock javascript %}

</head>

<body>
{% with request.resolver_match.kwargs as url_kwargs %}
<div class="header">
    <div class="center_content_header">
        <div class="logo">
            <i class="fas fa-check-circle"></i>
            <a href="{% url 'mainapp:main' %}">easytest</a>
        </div>

        <div class="menu">
            <ul>
                <li><a href="{% url 'mainapp:main' %}">{% trans 'На главную' %}</a></li>
                <li><a href="{% if user.is_staff %}#{% else %}{% url 'mainapp:tests' %}{% endif %}">{% trans 'Тесты' %}</a>
                    {% if user.is_staff %}
                        <ul>
                            <li><a href="{% url 'mainapp:tests_staff' %}">{% trans 'Мои тесты' %}</a></li>
                            <li><a href="{% url 'mainapp:test_create' %}">{% trans 'Создать тест' %}</a></li>
                        </ul>
                    {% endif %}
                </li>

                {% if user.is_authenticated %}
                    <li><a href="{% if user.is_staff %}#{% else %}{% url 'mainapp:results' user.id %}{% endif %}">{% trans 'Результаты' %}</a>
                        {% if user.is_staff %}
                            <ul>
                                <li><a href="{% url 'mainapp:results' user.id %}">{% trans 'Мои' %}</a>
                                <li><a href="{% url 'mainapp:groups' %}">{% trans 'Студентов' %}</a></li>
                            </ul>
                        {% endif %}
                    </li>
                {% endif %}

                {% if user.is_staff %}
                    <li><a href="{% url 'mainapp:groups' %}">{% trans 'Группы' %}</a></li>
                    <li><a href="{% url 'mainapp:students' %}">{% trans 'Студенты' %}</a></li>
                {% endif %}

                <li><a href="#">{% trans 'Контакты' %}</a></li>
            </ul>
        </div>

        <div class="menu">
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'auth:edit' %}">{% trans 'Привет, ' %}{{ user.first_name|default:user.username }}</a></li>
                    {% if user.is_staff %}
                        <li><a href="{% url 'admin:index' %}">{% trans 'Admin panel' %}</a></li>
                    {% endif %}
                    <li><a href="{% url 'auth:logout' %}">{% trans 'Выйти' %}</a></li>
                {% else %}
                    <li><a href="{% url 'auth:login' %}">{% trans 'Войти' %}</a></li>
                {% endif %}
            </ul>
        </div>

    </div>
</div>
<div class="content">
    {% block content %}
    {% endblock content %}
</div>
<div class="footer">
    <p>GeekUniversity Python 10/06/18</p>
</div>
{% endwith %}
</body>

</html>