easyTest/authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp
import os
from pathlib import PurePath

app_name = PurePath(os.path.dirname(__file__)).parts[-1]

urlpatterns = [
    path('login/', authapp.Login.as_view(), name='login'),
    path('logout/', authapp.Logout.as_view(), name='logout'),
    path('register/', authapp.CreateProfile.as_view(), name='register'),
    path('edit/', authapp.EditProfile.as_view(), name='edit'),
    path('password/edit', authapp.PasswordChange.as_view(), name='edit_password'),
]

easyTest/easyTest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('mainapp.urls', namespace='mainapp')),	
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

easyTest/authapp/models.py
# from django.db import models
# from django.contrib.auth.models import AbstractUser


# class ShopUser(AbstractUser):
#     avatar = models.ImageField(upload_to='users_avatars', blank=True, default='users_avatars/default_avatar.jpg')
#     age = models.PositiveIntegerField(verbose_name='age', null=True)

easyTest/authapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User


class MutualWidget:
    """Класс для добавления общих виджетов для форм"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class UserLoginForm(MutualWidget, AuthenticationForm):
    class Meta:
        model = User
        fields = '__all__'


class UserRegisterForm(MutualWidget, UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'password1', 'password2', 'email',)


class UserEditForm(MutualWidget, UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'email', 'password')

    def __init__(self, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

easyTest/authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import ugettext_lazy as _
from django.contrib import messages
from django.views.generic import CreateView, UpdateView, DeleteView
from authapp.forms import UserLoginForm, UserRegisterForm, UserEditForm
from django.contrib import auth
from django.contrib.auth.models import User
from django.urls import reverse_lazy


class Login(SuccessMessageMixin, UserPassesTestMixin, LoginView):
    """docstring for LoginView"""
    template_name = 'authapp/login.html'
    success_message = _('Log in success')
    form_class = UserLoginForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Log in')
        return context

    def test_func(self):
        return not self.request.user.is_authenticated

    def handle_no_permission(self):
        return HttpResponseRedirect('/')


class Logout(LogoutView):
    """docstring for logoutView"""
    success_message = _('Log out success')

    def get_next_page(self):
        next_page = super().get_next_page()
        if next_page:
            messages.success(self.request, self.success_message)
        return next_page


class CreateProfile(SuccessMessageMixin, CreateView):
    """docstring for RegisterProfile"""
    template_name = 'authapp/register.html'
    model = User
    form_class = UserRegisterForm
    success_url = '/'
    success_message = _('Registration completed successfully')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Register')
        return context

    def form_valid(self, form):
        form.instance.is_staff = True
        return super().form_valid(form)


class EditProfile(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """docstring for EditProfile"""
    template_name = 'authapp/edit.html'
    login_url = reverse_lazy('authapp:login')
    model = User
    form_class = UserEditForm
    success_url = '/'
    success_message = _('Profile changed')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Edit')
        return context


class DeleteProfile(DeleteView):
    """docstring for DelView"""
    model = User


class PasswordChange(LoginRequiredMixin, SuccessMessageMixin, PasswordChangeView):
    template_name = 'authapp/password_change_form.html'
    success_message = _('Password changed')
    success_url = reverse_lazy('authapp:edit')

easyTest/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load staticfiles i18n %}
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
        <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
        <link rel="stylesheet" href="{% static 'css/style_authapp.css' %}">
    {% endblock %}

</head>
<body>
	<div class="container">
         <div class="login">
            <div class="h2 text-center head">
                {% block name_page %}
                    {% trans 'Login to the system' %}
                {% endblock %}
            </div>
            {% block content %}
            {% endblock %}
        </div>
	</div>
</body>
</html>

easyTest/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load staticfiles i18n %}

{% block name_page %}
    {% trans 'Edit Profile' %}
{% endblock %}
{% block content %}
    <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="Save">
    </form>
    <a href="{% url 'authapp:edit_password' %}" class="">
        <button class="btn btn-round form-control">
            {% trans 'Change password' %}
        </button>
    </a>
    {% include 'authapp/includes/snip_button_home.html' %}

{% endblock %}

easyTest/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load staticfiles i18n %}
{% block title %}
    {{ title|title }}
{% endblock %}

{% block content %}
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Sign in">
    </form>
     <a href="{% url 'auth:register' %}" class="">
        <button class="btn btn form-control">
            {% trans 'Sign up' %}
        </button>
     </a>
    {% include 'authapp/includes/snip_button_home.html' %}
{% endblock %}

easyTest/authapp/templates/authapp/password_change_form.html
{% extends 'authapp/base.html' %}
{% load staticfiles i18n %}

{% block name_page %}
    {{ title }}
{% endblock %}
{% block content %}
    <form class="form-horizontal" action="{% url 'auth:edit_password' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="form-control" type="submit" value="Save">
    </form>
    {% include 'authapp/includes/snip_button_home.html' %}
{% endblock %}

easyTest/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load staticfiles i18n %}

{% block name_page %}
    {% trans 'Register Profile' %}
{% endblock %}
{% block content %}
    <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="Sign in">
    </form>
    {% include 'authapp/includes/snip_button_home.html' %}

{% endblock %}