easyTest/authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp
import os
from pathlib import PurePath

app_name = PurePath(os.path.dirname(__file__)).parts[-1]

urlpatterns = [
    path('login/', authapp.Login.as_view(), name='login'),
    path('logout/', authapp.Logout.as_view(), name='logout'),
    path('register/', authapp.CreateProfile.as_view(), name='register'),
    path('edit/', authapp.EditProfile.as_view(), name='edit'),
    path('password/edit', authapp.PasswordChange.as_view(), name='edit_password'),
]

easyTest/easyTest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('', include('mainapp.urls', namespace='mainapp')),	
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

easyTest/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp
from pathlib import PurePath
import os

app_name = PurePath(os.path.dirname(__file__)).parts[-1]

urlpatterns = [
    path('', mainapp.MainView.as_view(), name='main'),
    path('redirect/<slug:slug>/', mainapp.UsersRedirectView.as_view(), name='redirect'),

    path('test/create/', mainapp.TestCreate.as_view(), name='test_create'),
    path('test/edit/<int:pk>', mainapp.TestEdit.as_view(), name='test_edit'),
    path('test/<int:pk>', mainapp.QuestionList.as_view(), name='test'),
    path('test/<int:pk>/delete/', mainapp.TestDelete.as_view(), name='test_delete'),
    path('tests/', mainapp.TestList.as_view(), name='tests'),
    path('tests/staff/', mainapp.StaffTestList.as_view(), name='tests_staff'),
    path('test/<int:pk>/export/', mainapp.TestDetail.as_view(), name='test_export'),

    path('question_create/', mainapp.QuestionCreate.as_view(), name='question_create'),
    path('question_edit/<int:pk>/', mainapp.QuestionUpdate.as_view(), name='question_edit'),
    path('question/<int:pk>/delete/', mainapp.QuestionDelete.as_view(), name='question_delete'),
    path('question/staff/', mainapp.StaffQuestionList.as_view(), name='questions_staff'),

    path('results/<int:pk>/', mainapp.ResultList.as_view(), name='results'),
    path('result/<int:pk>/test_<int:test>', mainapp.ResultDetail.as_view(), name='result'),
    path('result/create/<int:test>/', mainapp.ResultCreate.as_view(), name='result_create'),
    path('result/edit/<int:test>/', mainapp.ResultUpdate.as_view(), name='result_update'),

    path('category/create/', mainapp.TestCategoryCreate.as_view(), name='category_create'),
    path('category/edit/<int:pk>', mainapp.TestCategoryEditView.as_view(), name='category_edit'),
    path('category/<int:pk>/delete/', mainapp.TestCategoryDelete.as_view(), name='testcategory_delete'),
    path('category/list/', mainapp.TestCategoryList.as_view(), name='testcategory_list'),

    path('test_time_is_over/<int:test>', mainapp.TestTimeIsOver.as_view(), name='test_time_is_over'),

    path('groups/', mainapp.GroupList.as_view(), name='groups'),
    path('group/create/', mainapp.GroupCreate.as_view(), name='group_create'),
    path('group/edit/<int:pk>/', mainapp.GroupUpdate.as_view(), name='group_update'),
    path('group/<int:pk>/delete/', mainapp.GroupDelete.as_view(), name='group_delete'),
    path('group/<int:pk>/', mainapp.GroupDetail.as_view(), name='group'),

    path('students/', mainapp.StudentList.as_view(), name='students'),
    path('student/create/', mainapp.StudentCreate.as_view(), name='student_create'),
    path('student/<int:pk>', mainapp.StudentUpdate.as_view(), name='student_update'),
    path('student/<int:pk>/delete/', mainapp.StudentDelete.as_view(), name='student_delete'),

    ]

easyTest/mainapp/views.py
import json
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView
from django.views.generic.edit import DeleteView
from django.views.generic.base import RedirectView
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from .models import *
import datetime
from mainapp.forms import TestForm, TestCategoryForm, QuestionForm, AnswerFormSet, GroupForm, StudentForm, StudentEditForm


class StaffPassesTestMixin(UserPassesTestMixin):
    """Миксин делает проверку пользователя на принадлежность к персоналу""" 
    raise_exception = True

    def test_func(self):
        return self.request.user.is_staff


class MainView(TemplateView):
    """Класс отображает главную страницу"""
    template_name = 'mainapp/index.html'


class UsersRedirectView(RedirectView):
    """Класс для автологина пользователей admin или test при нажатии на соответствующую ссылку"""
    pattern_name = 'mainapp:main'

    def get_redirect_url(self, *args, **kwargs):
        slug = self.kwargs['slug']
        slug_pass = slug
        students = ['Student_1', 'Student_2']
        if slug in students:
            slug_pass = 'studentpass1234'
        user = authenticate(username=slug, password=slug_pass)
        login(self.request, user)
        return super().get_redirect_url()


class QuestionList(LoginRequiredMixin, ListView):
    """docstring for test"""
    model = Question
    login_url = reverse_lazy('authapp:login')
    paginate_by = 1

    def get_queryset(self):
        return self.model.objects.get_test_questions(self.request, self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['test_title'] = self.model.objects.get_test_title(self.kwargs['pk'])
        return context


class StaffQuestionList(StaffPassesTestMixin, ListView):
    """Класс для просмотра всех созданных тестов пользователем"""
    model = Question
    template_name = 'mainapp/questions_staff_list.html'

    def get_queryset(self):
        return self.model.objects.get_questions(self.request)


class QuestionCreate(StaffPassesTestMixin, CreateView):
    """Класс создания вопроса с ответами"""
    model = Question
    form_class = QuestionForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['answers'] = AnswerFormSet()
        context['error_messages'] = self.kwargs.get('error_messages')
        if context['error_messages']:
            context['answers'] = AnswerFormSet(self.request.POST)
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        formset = AnswerFormSet(self.request.POST)

        if not formset.is_valid():
            self.kwargs['error_messages'] = formset.non_form_errors
            return self.form_invalid(form)
        else:
            formset.instance = form.save()
            return super().form_valid(formset)

    def get_success_url(self):
        return reverse_lazy('mainapp:questions_staff')


class QuestionUpdate(StaffPassesTestMixin, UpdateView):
    """Класс изменения вопроса"""
    model = Question
    form_class = QuestionForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['answers'] = AnswerFormSet(instance=self.get_object())
        context['error_messages'] = self.kwargs.get('error_messages')
        if self.request.POST:
            context['answers'] = AnswerFormSet(self.request.POST, instance=self.get_object())
        return context

    def form_valid(self, form):
        formset = AnswerFormSet(self.request.POST, instance=self.get_object())

        if not formset.is_valid():
            self.kwargs['error_messages'] = formset.non_form_errors
            return self.form_invalid(form)
        else:
            formset.instance = form.save()
            return super().form_valid(formset)

    def get_success_url(self):
        return reverse_lazy('mainapp:questions_staff')


class QuestionDelete(StaffPassesTestMixin, DeleteView):
    """Класс удаления вопроса"""
    model = Question
    success_url = reverse_lazy('mainapp:questions_staff')


class TestTimeIsOver(LoginRequiredMixin, ListView):
    template_name = 'mainapp/test_time_is_over.html'
    model = Question


class TestList(LoginRequiredMixin, ListView):
    model = Test
    login_url = reverse_lazy('authapp:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tests_without_result'] = []
        for result in Result.objects.get_results(self.request.user):
            context['tests_without_result'].append(result.test)
        return context

    def get_queryset(self):
        return self.model.objects.get_tests_by_group(self.request)


class StaffTestList(StaffPassesTestMixin, ListView):
    """Класс для просмотра всех созданных тестов пользователем"""
    model = Test
    template_name = 'mainapp/tests_staff_list.html'

    def get_queryset(self):
        return self.model.objects.get_tests(self.request)


class TestCreate(StaffPassesTestMixin, CreateView):
    """Класс создания нового теста"""
    model = Test
    form_class = TestForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Создать тест')
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request':self.request})
        return kwargs

    def form_valid(self, form):
        file = self.request.FILES.get('file')

        if file:
            form.clean(self.request)
            if not form.is_valid():
                return super().form_invalid(form)
            else:
                return HttpResponseRedirect(self.model.get_absolute_url(self))
        else:
            form.instance.owner = self.request.user
            response = super().form_valid(form)
            return response


class TestDetail(LoginRequiredMixin, StaffPassesTestMixin, UserPassesTestMixin, DetailView):
    """docstring for TestDetail"""
    model = Test
    slug_field = 'owner'
    login_url = reverse_lazy('authapp:login')

    def test_func(self):
        return self.get_object().owner == self.request.user

    def handle_no_permission(self):
        return HttpResponseRedirect(reverse_lazy('mainapp:tests_staff'))

    def get_success_url(self):
        return reverse_lazy('mainapp:tests_staff')

    def get_object(self):
        self.kwargs[self.slug_url_kwarg] = self.request.user
        response = super().get_object()
        return response

    def test_to_json(self):
        dict_test = {}
        test = self.get_object()
        dict_test['title'] = test.title
        dict_test['max_questions'] = test.max_questions
        dict_test['required_correct_answers'] = test.required_correct_answers
        dict_test['time'] = str(test.time)

        dict_test['questions'] = []
        for i, question in enumerate(test.questions.all()):
            dict_test['questions'].append(dict(description=question.description,
                                               q_type=question.q_type))
            dict_test['questions'][i]['answers'] = []
            for answer in question.answers.all():
                if question.q_type == 'select':
                    dict_test['questions'][i]['answers'].append(dict(description=answer.description,
                                                                     is_correct=answer.is_correct))
                elif question.q_type == 'sort':
                    dict_test['questions'][i]['answers'].append(dict(description=answer.description,
                                                                     order_number=answer.order_number))

        json_test = json.dumps(dict_test, indent=2, separators=(',', ': '), ensure_ascii=False)
        return json_test

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['file'] = self.test_to_json()
        return context


class TestEdit(TestDetail, UpdateView):
    """Класс изменения теста"""
    form_class = TestForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Изменить тест')
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request':self.request})
        return kwargs

    def form_valid(self, form):
        return TestCreate(request=self.request, args=self.args, kwargs=self.kwargs).form_valid(form)


class TestDelete(TestDetail, DeleteView):
    """Класс удаления теста"""
    pass


class TestCategoryCreate(StaffPassesTestMixin, CreateView):
    model = TestCategory
    form_class = TestCategoryForm

    def get_success_url(self):
        return reverse_lazy('mainapp:testcategory_list')


class TestCategoryEditView(StaffPassesTestMixin, UpdateView):
    """Класс изменения категории"""
    model = TestCategory
    form_class = TestCategoryForm

    def get_success_url(self):
        return reverse_lazy('mainapp:testcategory_list')


class TestCategoryList(StaffPassesTestMixin, ListView):
    """Класс для просмотра всех созданных категорий тестов пользователем"""
    model = TestCategory


class TestCategoryDelete(StaffPassesTestMixin, DeleteView):
    """Класс удаления категории теста"""
    model = TestCategory
    success_url = reverse_lazy('mainapp:main')


class ResultCreate(CreateView):
    """docstring for ResultCreate"""
    fields = '__all__'
    model = Result
    slug_url_kwarg = slug_field = 'test'

    def get_success_url(self):

easyTest/mainapp/templates/mainapp/answer_form.html
{% load static i18n %}

<div class="answers">
    <div class="card" style="width: 40rem;">
        <ul class="list-group list-group-flush">
            {% if object.answers %}
                {% for obj in object_list %}
                    <li class="list-group-item">
                        <div class="form-check">
                            <form method="post" action="">
                                {% csrf_token %}
                                <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios {% forloop.counter %}" value="option {% forloop.counter %}">
                                <label class="form-check-label" for="exampleRadios {% forloop.counter %}">
                                    {{ obj.title }}
                                </label>
                            </form>
                        </div>
                    </li>
                {% endfor %}
            {% endif %}
        </ul>
    </div>
</div>

easyTest/mainapp/templates/mainapp/group_list.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
    <title>{% trans 'Группы' %}</title>
{% endblock title%}

{% block content %}

    <div class="center_full">
        {% if object_list %}
            <h2>{% trans 'Выберите группу для просмотра результатов' %}</h2>

            <div class="list_container">
                {% for object in object_list %}
                    <div class="iter_list">
                        <a href="{% url 'mainapp:group' object.id %}">{{ object.title }}</a>
                        <a href="{% url 'mainapp:group_update' object.pk %}" class="a_button">{% trans 'Изменить' %}</a>
                        <form method="post" action="{% url 'mainapp:group_delete' object.pk %}">
                            {% csrf_token %}
                            <button class="base_link" type="submit">
                                {% trans 'Удалить' %}
                            </button>
                        </form>
                    </div>
                {% endfor %}
            </div>

        {% else %}
            <h2>{% trans 'Еще нет ни одной группы' %}</h2>
        {% endif %}
        <a class="btn btn-secondary" href="{% url 'mainapp:group_create' %}">{% trans 'Создать группу' %}</a>
    </div>

{% endblock content %}

easyTest/mainapp/templates/mainapp/index.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
    <title>{% trans 'Главная' %}</title>
{% endblock title%}

{% block content %}

    <div class="center_full">
        <div class="button_row">
        {% if user.is_staff %}
            <a href="{% url 'mainapp:tests_staff' %}">{% trans 'Пройти тест' %}</a>
        {% else %}
            <a href="{% url 'mainapp:tests' %}">{% trans 'Пройти тест' %}</a>
        {% endif %}
            {% if user.is_staff %}
                <a href="{% url 'mainapp:test_create' %}">{% trans 'Создать тест' %}</a>
            {% endif %}
        </div>

        <div class="button_row">
            <a href="{% url 'mainapp:redirect' 'Student_1' %}">{% trans 'Войти как студент №1' %}</a>
            <a href="{% url 'mainapp:redirect' 'Student_2' %}">{% trans 'Войти как студент №2' %}</a>
        </div>
        <div class="button_row">
            <a href="{% url 'mainapp:redirect' 'admin' %}">{% trans 'Войти преподавателем' %}</a>
        </div>
    </div>

{% endblock content %}

easyTest/mainapp/templates/mainapp/question_list.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
    <title>{% trans 'Тест' %}</title>
{% endblock title%}

{% block styles %}
{{block.super}}
<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">


{% endblock %}

{% block javascript %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/mainapp.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}" ></script>
    <script src="{% static 'js/touch_punch.js' %}"></script>

{% endblock javascript %}

{% block content %}

    <div class="center_full">
        {% for object in object_list %}
            <p><b>Тест "{{ test_title }}"</b></p>

            <div class="answer_list center"><b>{{ object.description }}</b><br>
                <form action="{% url 'mainapp:result_update' url_kwargs.pk %}" method="post">
                    {% csrf_token %}

                    <div class="answer_box">
                        {% if object.q_type == 'select' %}
                            {% with object.answers.get_correct_answer.count as count_correct %}
                                {% for answer in object.answers.all %}
                                    <div class="custom-control {% if count_correct == 1 %}custom-Radio{% else %}custom-checkbox{% endif %}">
                                        <input type="{% if count_correct == 1 %}Radio{% else %}checkbox{% endif %}"
                                               onchange="input_answer(this);return false;"
                                               name="answer_id"
                                               value="{{ answer.pk }}" id="select_{{ forloop.counter }}" class="custom-control-input">
                                        <label class="custom-control-label" for="select_{{ forloop.counter }}">{{ answer }}</label>
                                    </div>
                                {% endfor %}
                            {% endwith %}

                        {% elif object.q_type == 'sort' %}
                            <div class="row row_width_400">
                                <input type="hidden" name="skip_question" value="True">
                                <div class="col-sm-6" >
                                    <ul id="sortable1" class="connectedSortable col d-flex flex-column">
                                        {% for answer in object.answers.all %}
                                            <li class="ui-state-highlight">{{answer.description }}<input type="hidden" id="slider_input" name="answer_id" value="{{ answer.pk }}" /></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                                <div class="col-sm-6" >
                                    <ul id="sortable2" class="connectedSortable w-90 d-flex flex-column green_background">
                                    </ul>
                                </div>
                            </div>
                        {% endif %}
                    </div>

                    <input type="hidden" name="question_id" value="{{ object.pk }}">
                    <input type="hidden" id="left_time" name="left_time" value="">

                    {% if page_obj.has_next %}
                        <input type="hidden" name="href" value="{% url 'mainapp:test' url_kwargs.pk %}?page={{ page_obj.next_page_number }}">
                        <input type="hidden" name="href_current" value="{% url 'mainapp:test' url_kwargs.pk %}?page={{ page_obj.number }}">
                        <span class="center"><input type="submit" id="submit_skip" class="btn btn-secondary" value="Ответить позже"></span>
                    {% else %}
                        <input type="hidden" name="href" value="{% url 'mainapp:result' user.id url_kwargs.pk %}">
                    {% endif %}

                    <div class="timer_box">
                        <p id="timer">{{ request.session.test_time }}</p>
                        <p class="timer_pages">{{  page_obj.number }} / {{ paginator.num_pages }}</p>
                        <div class="sub">
                            <input type="submit" id="submit_b" class="btn btn-secondary" value="Далее">
                        </div>
                    </div>
                </form>
            </div>

        {% endfor %}
    </div>

{% endblock content %}

easyTest/mainapp/templates/mainapp/questions_staff_list.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
    <title>{% trans 'Созданные вопросы' %}</title>
{% endblock title%}

{% block content %}

    <div class="center_full">
        {% if object_list %}
            <p class="test_welcome">{% trans 'Список созданных Вами вопросов' %}</p>
            <div class="list_container">
                <table class="table table_result">
                    <thead>
                    <tr>
                        <th>№</th>
                        <th>{% trans 'Вопрос' %}</th>
                        <th>{% trans 'Используется в тестах' %}</th>
                        <th></th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for object in object_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td><a href="{% url 'mainapp:question_edit' object.pk %}">{{ object.description }}</a></td>
                            <td>
                                {{ object.get_related_tests }}
                            </td>
                            <td>
                                {% if object.get_related_tests == '-' %}
                                    <form method="post" action="{% url 'mainapp:question_delete' object.pk %}">
                                        {% csrf_token %}
                                        <button class="btn btn-secondary" type="submit">
                                            {% trans 'Удалить' %}
                                        </button>
                                    </form>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

        {% else %}
            <p class="test_welcome">{{ user.username|upper }}, {% trans 'Вы пока не создали ни одного вопроса '|upper %}</p>
        {% endif %}
            <a href="{% url 'mainapp:question_create' %}" class="btn btn-secondary">{% trans 'Создать вопрос' %}</a>
    </div>

{% endblock content %}

easyTest/mainapp/templates/mainapp/result_list.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
    <title>{% trans 'Результаты' %}</title>
{% endblock title%}

{% block content %}
    <div class="center_full">

        {% if object_list %}
            {% if student %}
                <h2>{% trans 'Результаты студента ' %}{{ student.first_name|default:student.username|title }}</h2>
            {% endif %}

            <b>{% trans 'Выберите тест, чтобы посмотреть результаты подробнее:' %}</b></p>
            <table class="table table_result">
                <thead>
                <tr>
                    <th>№</th>
                    <th>{% trans 'Тест' %}</th>
                    <th>{% trans 'Правильных ответов' %}</th>
                    <th>{% trans 'Время' %}</th>
                    <th>{% trans 'Результат' %}</th>
                </tr>
                </thead>

                <tbody>
                {% for object in object_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'mainapp:result' url_kwargs.pk object.test.pk %}">{{ object.test.title }}</a></td>
                        <td>{{ object.right_answers_count }}/{{ object.question_count }}</td>
                        <td>{{ object.time|date:"G:i:s" }}</td>
                        <td>
                            {% if object.is_test_passed %}<span class="text-success">{% trans 'Пройден' %}</span>
                            {% else %}<span class="text-danger">{% trans 'Не пройден' %}</span>{% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        {% elif url_kwargs.pk == user.id %}
            <h2>{{ user.first_name|default:user.username }}, {% trans 'Вы пока не прошли ни один тест' %}</h2>

            {% if user.is_staff %}
                <a href="{% url 'mainapp:tests_staff' %}" class="btn btn-secondary">{% trans 'Пройти тест' %}</a>
            {% else %}
                <a href="{% url 'mainapp:tests' %}" class="btn btn-secondary">{% trans 'Пройти тест' %}</a>
            {% endif %}

        {% else %}
            <h2>{{ student.first_name|default:student.username|title }} {% trans 'пока не прошел ни одного теста' %}</h2>
        {% endif %}

    </div>
{% endblock content %}

easyTest/mainapp/templates/mainapp/student_form.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
    <title>{% trans 'Студент' %}</title>
{% endblock title%}

{% block content %}

<div class="center_full">
    <form class="form_create" action="#" method="post">
        {% csrf_token %}
        {{ form }}
        <div class="center">
       		<input type="submit" name="#" value="{% trans 'Сохранить' %}" class="btn btn-secondary">
       	</div>
    </form>
</div>

{% endblock content %}

easyTest/mainapp/templates/mainapp/test_detail.html
<pre>{{ file }}</pre>

easyTest/mainapp/templates/mainapp/test_list.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
    <title>{% trans 'Тесты' %}</title>
{% endblock title%}

{% block content %}

    <div class="center_full">
        {% if object_list %}
            <h2>{% trans 'Выберите тест для прохождения' %}</h2>

            <table class="table table_test">
                <tbody>
                {% for group in user.student.in_groups.all %}
                    <th>{{ group.title }}</th>

                    {% for object in group.tests.all %}
                        <tr>
                            <td>
                                <form action="{% url 'mainapp:result_create' object.pk %}" method="post">
                                    {% csrf_token %}
                                    <input type="submit" name="test_name" value="{{ object.title }}" class="btn btn-link">
                                </form>
                            </td>

                            {% if object in tests_without_result %}
                                {% for result in user.results.all %}
                                    {% if result.test == object %}
                                        {% if result.is_test_passed %}<td class="text-success">{% trans 'Пройден' %}</td>
                                        {% else %}<td class="text-danger">{% trans 'Не пройден' %}</td>{% endif %}
                                    {% endif %}
                                {% endfor %}
                            {% else %}
                                <td class="text-danger">{% trans 'Не пройден' %}</td>
                            {% endif %}

                        </tr>
                    {% endfor %}

                {% endfor %}
                </tbody>
            </table>

        {% else %}
            <h2>{% trans 'Вам пока недоступны тесты для прохождения' %}</h2>
            <h2>{% trans 'Свяжитесь с преподавателем' %}</h2>
        {% endif %}
    </div>

{% endblock content %}

easyTest/mainapp/templates/mainapp/tests_staff_list.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
    <title>{% trans 'Созданные тесты' %}</title>
{% endblock title%}

{% block content %}

    <div class="center_full">
        {% if object_list %}
            <h2>{% trans 'Ваши тесты, '|upper %}{{ user.first_name|default:user.username }}</h2>

            <div class="list_container">
                {% for object in object_list %}
                    <div class="iter_list">

                        <form action="{% url 'mainapp:result_create' object.pk %}" method="post">
                            {% csrf_token %}
                            <input type="submit" name="test_name" value="{{ object.title }}" class="input_as_a">
                        </form>

                        <a href="{% url 'mainapp:test_edit' object.pk %}" class="a_button">{% trans 'Изменить' %}</a>

                        <form method="post" action="{% url 'mainapp:test_delete' object.pk %}">
                            {% csrf_token %}
                            <button class="base_link" type="submit">
                                {% trans 'Удалить' %}
                            </button>
                        </form>

                    </div>
                {% endfor %}
            </div>

        {% else %}
            <h2>{{ user.first_name|default:user.username }}, {% trans ' Вы пока не создали ни одного теста ' %}</h2>
        {% endif %}
        <a class="btn btn-secondary" href="{% url 'mainapp:test_create' %}">{% trans 'Создать тест' %}</a>
    </div>

{% endblock content %}

easyTest/mainapp/templates/mainapp/testscategory_list.html
{% extends "base.html" %}
{% load static i18n %}

{% block title %}
    <title>{% trans 'Созданные категории' %}</title>
{% endblock title%}

{% block content %}

    <div class="center_full">
        <div class="list_container">
            {% for object in object_list %}
	            <div class="iter_list">
		            <p class="list_title">{{ object.title }}</p>
					<a href="{% url 'mainapp:category_edit' object.pk %}" class="base_link">{% trans 'Изменить' %}</a>
		            <form method="post" action="{% url 'mainapp:testcategory_delete' object.pk %}">
			            {% csrf_token %}
    		            <button class="base_link" type="submit">
    			            {% trans 'Удалить' %}
    		            </button>
		            </form>
	            </div>
            {% endfor %}
        </div>
    </div>

{% endblock content %}